---
  - name: Create a directory for app if it does not exist
    file:
      path: /home/{{ user }}/Posthog
      state: directory
      mode: '0755'

  - name: Clone Posthog from repository
    git:
      repo: '{{ repository }}'
      dest: /home/{{ user }}/Posthog
      version: 'master'
      update: true
